version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing Docker...
      - apt-get update -y
      - apt-get install -y docker.io
      - nohup /usr/bin/dockerd > /dev/null 2>&1 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Docker installed and started successfully
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654589924.dkr.ecr.us-east-1.amazonaws.com/grupo1container
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t testcontaineregistry1 -f Empresa.App.Service.WebApi/Dockerfile .
      - docker tag testcontaineregistry1:latest 654654589924.dkr.ecr.us-east-1.amazonaws.com/grupo1container:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 654654589924.dkr.ecr.us-east-1.amazonaws.com/grupo1container:latest
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"grupo1containersalud","imageUri":"654654589924.dkr.ecr.us-east-1.amazonaws.com/grupo1container:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json